name: 🐞 Bug report
description: "Problems encountered while utilizing Yi model"
title: "Title "
labels: ["type/bug-report"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your contribution!
  - type: checkboxes
    attributes:
      label: Reminder
      description: >
        Please search [Github Discussion](https://github.com/01-ai/Yi/discussions) and [issues](https://github.com/01-ai/Yi/issues) carefully.
      options:
        - label: >
            I have searched the Github Discussion and issues and have not found anything similar to this.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Python**: 3.10
          - **PyTorch**: 2.0.1+cu118
          - **CUDA**: 11.8
      value: |
        - OS:
        - Python:
        - PyTorch:
        - CUDA:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: |
        A concise description of what you're experiencing, with screenshot attached if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
