name: 🚀 Feature request
description: Add new feature, improve code, and more
labels:
  - "type/feature-request"
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your ideas!
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search [issues](https://github.com/01-ai/Yi/discussions) to check if your issue has already been reported.
      options:
        - label: >
            I searched in the [issues](https://github.com/01-ai/Yi/discussions) and found nothing similar.
          required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Describe the motivations for this enhancement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe the proposed solution and add related materials like links if any.
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe other alternative solutions or features you considered, but rejected.
  - type: textarea
    attributes:
      label: Anything else?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We look forward to the community of developers or users helping solve Pulsar problems together. If you are willing to submit a PR to implement the enhancement, please check the box.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"