name: 📚 Document
description: Suggest document changes
title: "[Doc] "
labels: ["doc-required"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your ideas!
  - type: checkboxes
    attributes:
      label: Reminder
      description: >
        Please ensure you have read the README carefully and searched the existing [issues](https://github.com/01-ai/Yi/discussions).
      options:
        - label: >
            I have read the README and searched the existing [issues](https://github.com/01-ai/Yi/discussions).
          required: true
  - type: textarea
    attributes:
      label: What issue do you find in Yi docs?
      description: For example, something missing, inaccurate, incomplete, hard to use/understand/find, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your suggestion?
      description: For example, add explanations, correct descriptions, delete information, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any reference?
      description: (For example, website links, etc)?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We look forward to the community of developers or users helping improve Yi document together. If you are willing to submit a PR, please check the box.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
