name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  basic-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install linting libraries
        run: pip install autoflake isort black
      - name: Autoflake
        run: |
          output="$(autoflake . --remove-all-unused-imports --remove-unused-variables --expand-star-imports --ignore-init-module-imports -r)"
          if [[ -n $output ]]
          then
          printf "%s\n" "$output"
          exit 1
          else
          exit 0
          fi
      - name: Isort
        run: isort . --profile black --check-only --diff
      - name: Black
        run: black . --diff --color --check

  # build-and-push:
  #   needs: basic-check
  #   runs-on:
  #     - arc
  #     - cpu
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Set proxy
  #       run: |
  #         echo "http_proxy=$http_proxy" >> $GITHUB_ENV
  #         echo "https_proxy=$https_proxy" >> $GITHUB_ENV
  #     - uses: 01-ai/actions/build_docker_image@main
  #       id: build-and-push
  #       with:
  #         registry: ${{ vars.VOLCES_REGISTRY }}
  #         namespace: ${{ vars.VOLCES_NAMESPACE }}
  #         tags: 'latest'
  #         username: ${{ secrets.VOLCES_USER }}
  #         password: ${{ secrets.VOLCES_TOKEN }}