name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main  
      - name: Basic check
        uses: ./actions/lint

  build-and-push:
    runs-on:
      - cpu
      - arc
    needs: basic-check
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main
      - name: Build Docker Image
        uses: ./actions/build_docker_image
        with:
          registry: ${{ secrets.DEFAULT_REGISTRY }}
          namespace: ci
          tags: latest
          username: ${{ secrets.DEFAULT_REGISTRY_USER }}
          password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}