name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  basic-check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.read_version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main  
      - name: Basic check
        uses: ./actions/lint
      # https://github.com/actions/checkout/issues/692#issuecomment-1502203573
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main  
      # try to create a tag
      - uses: SebRollen/toml-action@v1.0.2
        id: read_version
        with:
          file: "pyproject.toml"
          field: "tool.poetry.version"
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        if: (github.ref_name == github.event.repository.default_branch) && !contains(steps.read_version.outputs.value, '-')
        with:
          tag: ${{ steps.read_version.outputs.value }}

  build-and-push:
    runs-on:
      - public
    needs: basic-check
    outputs:
      primary_tag: ${{ steps.build-and-push.outputs.primary_tag }}
      matrix: ${{ steps.build-and-push.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main
      - name: Set proxy
        run: |
          echo "http_proxy=$http_proxy" >> $GITHUB_ENV
          echo "https_proxy=$https_proxy" >> $GITHUB_ENV
      - name: Build Docker Image
        id: build-and-push
        uses: ./actions/build_docker_image
        with:
          registry: ${{ secrets.DEFAULT_REGISTRY }}
          namespace: ci
          tags: ${{ needs.basic-check.outputs.tag }}
          username: ${{ secrets.DEFAULT_REGISTRY_USER }}
          password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}

  sync-docker-images-to-github:
    needs: build-and-push
    strategy:
        matrix: ${{ fromJSON(needs.build-and-push.outputs.matrix) }}
    runs-on: public
    steps:
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main
      - id: meta
        run: |
          echo "src_path=$(echo '${{ matrix.tag }}' | cut -d '/' -f3- | cut -d ':' -f1 )" >> "$GITHUB_OUTPUT"
          echo "src_tag=$(echo '${{ matrix.tag }}' | cut -d ':' -f2 )" >> "$GITHUB_OUTPUT"
      - uses: ./actions/sync_docker_image
        with:
          src_registry: ${{ secrets.DEFAULT_REGISTRY }}
          src_namespace: ci
          src_path: ${{ steps.meta.outputs.src_path }}
          src_tag: ${{ steps.meta.outputs.src_tag }}
          src_username: ${{ secrets.DEFAULT_REGISTRY_USER }}
          src_password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}
          dest_registry: ghcr.io
          dest_namespace: 01-ai
          dest_username: ${{ github.actor }}
          dest_password: ${{ secrets.GITHUB_TOKEN }}

  sync-docker-images-to-public:
    needs: build-and-push
    strategy:
        matrix: ${{ fromJSON(needs.build-and-push.outputs.matrix) }}
    runs-on: public
    steps:
      - name: Checkout Actions 
        uses: actions/checkout@v3 
        with: 
          repository: 01-ai/actions
          token: ${{ secrets.PAT_TO_CLONE_ACTIONS }} 
          path: actions
          ref: main
      - id: meta
        run: |
          echo "src_path=$(echo '${{ matrix.tag }}' | cut -d '/' -f3- | cut -d ':' -f1 )" >> "$GITHUB_OUTPUT"
          echo "src_tag=$(echo '${{ matrix.tag }}' | cut -d ':' -f2 )" >> "$GITHUB_OUTPUT"
      - uses: ./actions/sync_docker_image
        with:
          src_registry: ${{ secrets.DEFAULT_REGISTRY }}
          src_namespace: ci
          src_path: ${{ steps.meta.outputs.src_path }}
          src_tag: ${{ steps.meta.outputs.src_tag }}
          src_username: ${{ secrets.DEFAULT_REGISTRY_USER }}
          src_password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}
          dest_registry: ghcr.io
          dest_namespace: 01-ai
          dest_username: ${{ github.actor }}
          dest_password: ${{ secrets.GITHUB_TOKEN }}