name: Sync README to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['Yi-6B', 'Yi-34B', 'Yi-34B-200K', 'Yi-6B-200K']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Sync README for ${{ matrix.repo }}
      run: |
        GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/01-ai/${{ matrix.repo }}
        cp HUGGINGFACE_README.md ${{ matrix.repo }}/README.md
        cd ${{ matrix.repo }}
        git config --global user.email "bot@01.ai"
        git config --global user.name "01-ai-bot"
        
        # Check for changes
        if git diff --quiet; then
          echo "No changes to commit for ${{ matrix.repo }}"
        else
          git add README.md
          git commit -m "Sync README"
          git push https://shiyue-loop:${{ secrets.HF_TOKEN }}@huggingface.co/01-ai/${{ matrix.repo }}
        fi
